### ISSUE TITLE
Change the plugin folder name to rollouts-opsmx-log-metric-plugin

### ISSUE THREAD

**Issue by balajisiva** [argoproj-labs/rollouts-opsmx-metric-plugin#2]
can we change the plugin folder name to rollouts-opsmx-log-metric-plugin so that it reflects the use case better as OpsMx pluging supports  both log and metrics providers.  @zachaller

**Comment by zachaller** [comment]
So we are actually trying to implement this as a standard naming convention https://github.com/argoproj/argo-rollouts/blob/8681fe57935ec297283342e0d2469c2b4f494b49/docs/plugins.md

```
There will also be a standard for naming repositories under argoproj-labs in the
form of rollouts-<tool>-<type>-plugin where <type> is say metric, or trafficrouter and <tool> is the software 
the plugin is for say nginx.
```

However on the docs page here https://argo-rollouts.readthedocs.io/en/latest/analysis/plugins/#list-of-available-plugins-alphabetical-order you will be able to have it called what you want as well as add a description.

**Comment by zachaller** [comment]
We could do this if you would prefer though as well `rollouts-opsmx_log-metric-plugin` if you would prefer that though personally it feels a bit strange to me with the standard convention but up to you. The ask would be that the <tool> portion use _ to separate words

**Comment by balajisiva** [comment]
ok. I will close this.
